### ISSUE TITLE
make repository update before installing nscd

### ISSUE THREAD

**Issue by rauschbit** [ghoneycutt/puppet-module-nscd#11]
i wanted to test your nscd module for our productive environment but have the problem that there is no linux-repository update (like "apt-get update") before installing the nscd-package...
would be nice if you could implement that in your module!
maybe advancing your "osfamily" case with a new variable (like "$os_repo_update = 'apt-get update'") for the os specific repository update command and an additional "require => Exec[$os_repo_update]," in the package installatoin would be a solution?
thx in advance!

**Comment by ghoneycutt** [comment]
This should be handled elsewhere in code related to the package manager instead of nscd.
