### ISSUE TITLE
Add support for SLES 15 

### ISSUE THREAD

**Issue by absld** [ghoneycutt/puppet-module-nscd#59]
There should be no differences to SUSE SLES 12

**Comment by ghoneycutt** [comment]
Have you tried this module on SLES 15 and verified it works?

**Comment by absld** [comment]
Hi, yes. Made a fork and tested it on SLES 15. There are no differences to SLES 12. Made a pull request :-)

**Comment by ghoneycutt** [comment]
Thanks again! Released in v1.13.0
